name: CI

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: alert_dispatcher
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Build & Unit Tests
        run: ./mvnw test
        env:
          SPRING_PROFILES_ACTIVE: ci
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Start app in background
        run: ./mvnw spring-boot:run > app.log 2>&1 &
        env:
          SPRING_PROFILES_ACTIVE: ci
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Wait for app
        run: |
          for i in {1..30}; do
            curl -sf http://localhost:8080/actuator/health && echo "App ready" && break
            echo "Waiting... ($i)"
            sleep 3
          done

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        run: |
          newman run postman/CI.postman_collection.json \
            -e postman/CI.postman_environment.json \
            --reporters cli,junit \
            --reporter-junit-export results/newman.xml

      - name: Publish results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: API Tests
          path: results/newman.xml
          reporter: java-junit